#!/bin/bash
# WSL2-Optimized Playwright Environment Configuration
# Generated by Claude Code Recovery Plan

# Virtual Display Configuration (no X11 server needed)
export DISPLAY=:99

# Playwright Browser Configuration
export PLAYWRIGHT_BROWSERS_PATH=/home/robne/.cache/ms-playwright-new
export PLAYWRIGHT_SKIP_BROWSER_GC=1
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0

# WSL2-Specific Optimizations
export PLAYWRIGHT_LAUNCH_OPTIONS_ARGS='["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-gpu", "--headless=new"]'
export PLAYWRIGHT_CHROMIUM_USE_HEADLESS_NEW=1

# Memory and Performance
export NODE_OPTIONS="--max-old-space-size=4096"
export PLAYWRIGHT_REPORTERS="dot"

# Debugging (can be disabled after successful setup)
export DEBUG=pw:api

# WSL2 Library Path Workaround (if needed)
# export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

echo "✅ WSL2 Playwright environment loaded"
echo "🌐 Browser path: $PLAYWRIGHT_BROWSERS_PATH"
echo "🔧 Headless mode: enabled with optimized args"