/**
 * i18n Configuration
 *
 * Defines supported locales, default locale, and locale validation
 * Auto-generated by scripts/install-all-languages.js
 */

export type SupportedLocale = 
  | "af-ZA"
  | "am-ET"
  | "ar-AE"
  | "ar-SA"
  | "az-AZ"
  | "be-BY"
  | "bg-BG"
  | "bn-BD"
  | "bn-IN"
  | "bs-BA"
  | "ca-ES"
  | "cs-CZ"
  | "cy-GB"
  | "da-DK"
  | "de-AT"
  | "de-CH"
  | "de-DE"
  | "el-GR"
  | "en-AU"
  | "en-CA"
  | "en-GB"
  | "en-IE"
  | "en-IN"
  | "en-NZ"
  | "en-SG"
  | "en-US"
  | "en-ZA"
  | "es-AR"
  | "es-BO"
  | "es-CL"
  | "es-CO"
  | "es-CR"
  | "es-DO"
  | "es-EC"
  | "es-ES"
  | "es-GT"
  | "es-HN"
  | "es-MX"
  | "es-NI"
  | "es-PA"
  | "es-PE"
  | "es-PR"
  | "es-PY"
  | "es-SV"
  | "es-US"
  | "es-UY"
  | "es-VE"
  | "et-EE"
  | "eu-ES"
  | "fa-IR"
  | "fi-FI"
  | "fil-PH"
  | "fr-BE"
  | "fr-CA"
  | "fr-CH"
  | "fr-FR"
  | "gl-ES"
  | "gu-IN"
  | "he-IL"
  | "hi-IN"
  | "hr-HR"
  | "hu-HU"
  | "hy-AM"
  | "id-ID"
  | "is-IS"
  | "it-CH"
  | "it-IT"
  | "ja-JP"
  | "ka-GE"
  | "kk-KZ"
  | "km-KH"
  | "kn-IN"
  | "ko-KR"
  | "ky-KG"
  | "lo-LA"
  | "lt-LT"
  | "lv-LV"
  | "mk-MK"
  | "ml-IN"
  | "mn-MN"
  | "mr-IN"
  | "ms-MY"
  | "my-MM"
  | "nb-NO"
  | "ne-NP"
  | "nl-BE"
  | "nl-NL"
  | "pa-IN"
  | "pl-PL"
  | "pt-BR"
  | "pt-PT"
  | "ro-RO"
  | "ru-RU"
  | "si-LK"
  | "sk-SK"
  | "sl-SI"
  | "sq-AL"
  | "sr-RS"
  | "sv-SE"
  | "sw-TZ"
  | "ta-IN"
  | "te-IN"
  | "th-TH"
  | "tr-TR"
  | "uk-UA"
  | "ur-PK"
  | "uz-UZ"
  | "vi-VN"
  | "zh-CN"
  | "zh-HK"
  | "zh-TW"
  | "zu-ZA";

/**
 * Supported locales
 */
export const SUPPORTED_LOCALES: SupportedLocale[] = [
  "af-ZA",
  "am-ET",
  "ar-AE",
  "ar-SA",
  "az-AZ",
  "be-BY",
  "bg-BG",
  "bn-BD",
  "bn-IN",
  "bs-BA",
  "ca-ES",
  "cs-CZ",
  "cy-GB",
  "da-DK",
  "de-AT",
  "de-CH",
  "de-DE",
  "el-GR",
  "en-AU",
  "en-CA",
  "en-GB",
  "en-IE",
  "en-IN",
  "en-NZ",
  "en-SG",
  "en-US",
  "en-ZA",
  "es-AR",
  "es-BO",
  "es-CL",
  "es-CO",
  "es-CR",
  "es-DO",
  "es-EC",
  "es-ES",
  "es-GT",
  "es-HN",
  "es-MX",
  "es-NI",
  "es-PA",
  "es-PE",
  "es-PR",
  "es-PY",
  "es-SV",
  "es-US",
  "es-UY",
  "es-VE",
  "et-EE",
  "eu-ES",
  "fa-IR",
  "fi-FI",
  "fil-PH",
  "fr-BE",
  "fr-CA",
  "fr-CH",
  "fr-FR",
  "gl-ES",
  "gu-IN",
  "he-IL",
  "hi-IN",
  "hr-HR",
  "hu-HU",
  "hy-AM",
  "id-ID",
  "is-IS",
  "it-CH",
  "it-IT",
  "ja-JP",
  "ka-GE",
  "kk-KZ",
  "km-KH",
  "kn-IN",
  "ko-KR",
  "ky-KG",
  "lo-LA",
  "lt-LT",
  "lv-LV",
  "mk-MK",
  "ml-IN",
  "mn-MN",
  "mr-IN",
  "ms-MY",
  "my-MM",
  "nb-NO",
  "ne-NP",
  "nl-BE",
  "nl-NL",
  "pa-IN",
  "pl-PL",
  "pt-BR",
  "pt-PT",
  "ro-RO",
  "ru-RU",
  "si-LK",
  "sk-SK",
  "sl-SI",
  "sq-AL",
  "sr-RS",
  "sv-SE",
  "sw-TZ",
  "ta-IN",
  "te-IN",
  "th-TH",
  "tr-TR",
  "uk-UA",
  "ur-PK",
  "uz-UZ",
  "vi-VN",
  "zh-CN",
  "zh-HK",
  "zh-TW",
  "zu-ZA"
];

export const DEFAULT_LOCALE: SupportedLocale = "en-US";

/**
 * Locale metadata for display and formatting
 */
export const LOCALE_METADATA = {
  "af-ZA": {
    label: "Afrikaans",
    dir: "ltr",
    currency: "ZAR",
    numberingSystem: "standard",
  },
  "am-ET": {
    label: "Amharic",
    dir: "ltr",
    currency: "ETB",
    numberingSystem: "standard",
  },
  "ar-AE": {
    label: "Arabic (UAE)",
    dir: "rtl",
    currency: "AED",
    numberingSystem: "standard",
  },
  "ar-SA": {
    label: "Arabic (Saudi Arabia)",
    dir: "rtl",
    currency: "SAR",
    numberingSystem: "standard",
  },
  "az-AZ": {
    label: "Azerbaijani",
    dir: "ltr",
    currency: "AZN",
    numberingSystem: "standard",
  },
  "be-BY": {
    label: "Belarusian",
    dir: "ltr",
    currency: "BYN",
    numberingSystem: "standard",
  },
  "bg-BG": {
    label: "Bulgarian",
    dir: "ltr",
    currency: "BGN",
    numberingSystem: "standard",
  },
  "bn-BD": {
    label: "Bengali (Bangladesh)",
    dir: "ltr",
    currency: "BDT",
    numberingSystem: "standard",
  },
  "bn-IN": {
    label: "Bengali (India)",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "bs-BA": {
    label: "Bosnian",
    dir: "ltr",
    currency: "BAM",
    numberingSystem: "standard",
  },
  "ca-ES": {
    label: "Catalan",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "cs-CZ": {
    label: "Czech",
    dir: "ltr",
    currency: "CZK",
    numberingSystem: "standard",
  },
  "cy-GB": {
    label: "Welsh",
    dir: "ltr",
    currency: "GBP",
    numberingSystem: "standard",
  },
  "da-DK": {
    label: "Danish",
    dir: "ltr",
    currency: "DKK",
    numberingSystem: "standard",
  },
  "de-AT": {
    label: "German (Austria)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "de-CH": {
    label: "German (Switzerland)",
    dir: "ltr",
    currency: "CHF",
    numberingSystem: "standard",
  },
  "de-DE": {
    label: "German (Germany)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "el-GR": {
    label: "Greek",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "en-AU": {
    label: "English (Australia)",
    dir: "ltr",
    currency: "AUD",
    numberingSystem: "standard",
  },
  "en-CA": {
    label: "English (Canada)",
    dir: "ltr",
    currency: "CAD",
    numberingSystem: "standard",
  },
  "en-GB": {
    label: "English (UK)",
    dir: "ltr",
    currency: "GBP",
    numberingSystem: "standard",
  },
  "en-IE": {
    label: "English (Ireland)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "en-IN": {
    label: "English (India)",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "en-NZ": {
    label: "English (New Zealand)",
    dir: "ltr",
    currency: "NZD",
    numberingSystem: "standard",
  },
  "en-SG": {
    label: "English (Singapore)",
    dir: "ltr",
    currency: "SGD",
    numberingSystem: "standard",
  },
  "en-US": {
    label: "English (US)",
    dir: "ltr",
    currency: "USD",
    numberingSystem: "standard",
  },
  "en-ZA": {
    label: "English (South Africa)",
    dir: "ltr",
    currency: "ZAR",
    numberingSystem: "standard",
  },
  "es-AR": {
    label: "Spanish (Argentina)",
    dir: "ltr",
    currency: "ARS",
    numberingSystem: "standard",
  },
  "es-BO": {
    label: "Spanish (Bolivia)",
    dir: "ltr",
    currency: "BOB",
    numberingSystem: "standard",
  },
  "es-CL": {
    label: "Spanish (Chile)",
    dir: "ltr",
    currency: "CLP",
    numberingSystem: "standard",
  },
  "es-CO": {
    label: "Spanish (Colombia)",
    dir: "ltr",
    currency: "COP",
    numberingSystem: "standard",
  },
  "es-CR": {
    label: "Spanish (Costa Rica)",
    dir: "ltr",
    currency: "CRC",
    numberingSystem: "standard",
  },
  "es-DO": {
    label: "Spanish (Dominican Republic)",
    dir: "ltr",
    currency: "DOP",
    numberingSystem: "standard",
  },
  "es-EC": {
    label: "Spanish (Ecuador)",
    dir: "ltr",
    currency: "USD",
    numberingSystem: "standard",
  },
  "es-ES": {
    label: "Spanish (Spain)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "es-GT": {
    label: "Spanish (Guatemala)",
    dir: "ltr",
    currency: "GTQ",
    numberingSystem: "standard",
  },
  "es-HN": {
    label: "Spanish (Honduras)",
    dir: "ltr",
    currency: "HNL",
    numberingSystem: "standard",
  },
  "es-MX": {
    label: "Spanish (Mexico)",
    dir: "ltr",
    currency: "MXN",
    numberingSystem: "standard",
  },
  "es-NI": {
    label: "Spanish (Nicaragua)",
    dir: "ltr",
    currency: "NIO",
    numberingSystem: "standard",
  },
  "es-PA": {
    label: "Spanish (Panama)",
    dir: "ltr",
    currency: "USD",
    numberingSystem: "standard",
  },
  "es-PE": {
    label: "Spanish (Peru)",
    dir: "ltr",
    currency: "PEN",
    numberingSystem: "standard",
  },
  "es-PR": {
    label: "Spanish (Puerto Rico)",
    dir: "ltr",
    currency: "USD",
    numberingSystem: "standard",
  },
  "es-PY": {
    label: "Spanish (Paraguay)",
    dir: "ltr",
    currency: "PYG",
    numberingSystem: "standard",
  },
  "es-SV": {
    label: "Spanish (El Salvador)",
    dir: "ltr",
    currency: "USD",
    numberingSystem: "standard",
  },
  "es-US": {
    label: "Spanish (US)",
    dir: "ltr",
    currency: "USD",
    numberingSystem: "standard",
  },
  "es-UY": {
    label: "Spanish (Uruguay)",
    dir: "ltr",
    currency: "UYU",
    numberingSystem: "standard",
  },
  "es-VE": {
    label: "Spanish (Venezuela)",
    dir: "ltr",
    currency: "VES",
    numberingSystem: "standard",
  },
  "et-EE": {
    label: "Estonian",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "eu-ES": {
    label: "Basque",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "fa-IR": {
    label: "Persian",
    dir: "rtl",
    currency: "IRR",
    numberingSystem: "standard",
  },
  "fi-FI": {
    label: "Finnish",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "fil-PH": {
    label: "Filipino",
    dir: "ltr",
    currency: "PHP",
    numberingSystem: "standard",
  },
  "fr-BE": {
    label: "French (Belgium)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
    },
  "fr-CA": {
    label: "French (Canada)",
    dir: "ltr",
    currency: "CAD",
    numberingSystem: "standard",
  },
  "fr-CH": {
    label: "French (Switzerland)",
    dir: "ltr",
    currency: "CHF",
    numberingSystem: "standard",
  },
  "fr-FR": {
    label: "French (France)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "gl-ES": {
    label: "Galician",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "gu-IN": {
    label: "Gujarati",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "he-IL": {
    label: "Hebrew",
    dir: "rtl",
    currency: "ILS",
    numberingSystem: "standard",
  },
  "hi-IN": {
    label: "Hindi",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "hr-HR": {
    label: "Croatian",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "hu-HU": {
    label: "Hungarian",
    dir: "ltr",
    currency: "HUF",
    numberingSystem: "standard",
  },
  "hy-AM": {
    label: "Armenian",
    dir: "ltr",
    currency: "AMD",
    numberingSystem: "standard",
  },
  "id-ID": {
    label: "Indonesian",
    dir: "ltr",
    currency: "IDR",
    numberingSystem: "standard",
  },
  "is-IS": {
    label: "Icelandic",
    dir: "ltr",
    currency: "ISK",
    numberingSystem: "standard",
  },
  "it-CH": {
    label: "Italian (Switzerland)",
    dir: "ltr",
    currency: "CHF",
    numberingSystem: "standard",
  },
  "it-IT": {
    label: "Italian (Italy)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "ja-JP": {
    label: "Japanese",
    dir: "ltr",
    currency: "JPY",
    numberingSystem: "standard",
  },
  "ka-GE": {
    label: "Georgian",
    dir: "ltr",
    currency: "GEL",
    numberingSystem: "standard",
  },
  "kk-KZ": {
    label: "Kazakh",
    dir: "ltr",
    currency: "KZT",
    numberingSystem: "standard",
  },
  "km-KH": {
    label: "Khmer",
    dir: "ltr",
    currency: "KHR",
    numberingSystem: "standard",
  },
  "kn-IN": {
    label: "Kannada",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "ko-KR": {
    label: "Korean",
    dir: "ltr",
    currency: "KRW",
    numberingSystem: "standard",
  },
  "ky-KG": {
    label: "Kyrgyz",
    dir: "ltr",
    currency: "KGS",
    numberingSystem: "standard",
  },
  "lo-LA": {
    label: "Lao",
    dir: "ltr",
    currency: "LAK",
    numberingSystem: "standard",
  },
  "lt-LT": {
    label: "Lithuanian",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "lv-LV": {
    label: "Latvian",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "mk-MK": {
    label: "Macedonian",
    dir: "ltr",
    currency: "MKD",
    numberingSystem: "standard",
  },
  "ml-IN": {
    label: "Malayalam",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "mn-MN": {
    label: "Mongolian",
    dir: "ltr",
    currency: "MNT",
    numberingSystem: "standard",
  },
  "mr-IN": {
    label: "Marathi",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "ms-MY": {
    label: "Malay",
    dir: "ltr",
    currency: "MYR",
    numberingSystem: "standard",
  },
  "my-MM": {
    label: "Burmese",
    dir: "ltr",
    currency: "MMK",
    numberingSystem: "standard",
  },
  "nb-NO": {
    label: "Norwegian Bokmål",
    dir: "ltr",
    currency: "NOK",
    numberingSystem: "standard",
  },
  "ne-NP": {
    label: "Nepali",
    dir: "ltr",
    currency: "NPR",
    numberingSystem: "standard",
  },
  "nl-BE": {
    label: "Dutch (Belgium)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "nl-NL": {
    label: "Dutch (Netherlands)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "pa-IN": {
    label: "Punjabi",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "pl-PL": {
    label: "Polish",
    dir: "ltr",
    currency: "PLN",
    numberingSystem: "standard",
  },
  "pt-BR": {
    label: "Portuguese (Brazil)",
    dir: "ltr",
    currency: "BRL",
    numberingSystem: "standard",
  },
  "pt-PT": {
    label: "Portuguese (Portugal)",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "ro-RO": {
    label: "Romanian",
    dir: "ltr",
    currency: "RON",
    numberingSystem: "standard",
  },
  "ru-RU": {
    label: "Russian",
    dir: "ltr",
    currency: "RUB",
    numberingSystem: "standard",
  },
  "si-LK": {
    label: "Sinhala",
    dir: "ltr",
    currency: "LKR",
    numberingSystem: "standard",
  },
  "sk-SK": {
    label: "Slovak",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "sl-SI": {
    label: "Slovenian",
    dir: "ltr",
    currency: "EUR",
    numberingSystem: "standard",
  },
  "sq-AL": {
    label: "Albanian",
    dir: "ltr",
    currency: "ALL",
    numberingSystem: "standard",
  },
  "sr-RS": {
    label: "Serbian",
    dir: "ltr",
    currency: "RSD",
    numberingSystem: "standard",
  },
  "sv-SE": {
    label: "Swedish",
    dir: "ltr",
    currency: "SEK",
    numberingSystem: "standard",
  },
  "sw-TZ": {
    label: "Swahili",
    dir: "ltr",
    currency: "TZS",
    numberingSystem: "standard",
  },
  "ta-IN": {
    label: "Tamil",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "te-IN": {
    label: "Telugu",
    dir: "ltr",
    currency: "INR",
    numberingSystem: "standard",
  },
  "th-TH": {
    label: "Thai",
    dir: "ltr",
    currency: "THB",
    numberingSystem: "standard",
  },
  "tr-TR": {
    label: "Turkish",
    dir: "ltr",
    currency: "TRY",
    numberingSystem: "standard",
  },
  "uk-UA": {
    label: "Ukrainian",
    dir: "ltr",
    currency: "UAH",
    numberingSystem: "standard",
  },
  "ur-PK": {
    label: "Urdu",
    dir: "rtl",
    currency: "PKR",
    numberingSystem: "standard",
  },
  "uz-UZ": {
    label: "Uzbek",
    dir: "ltr",
    currency: "UZS",
    numberingSystem: "standard",
  },
  "vi-VN": {
    label: "Vietnamese",
    dir: "ltr",
    currency: "VND",
    numberingSystem: "standard",
  },
  "zh-CN": {
    label: "Chinese (Simplified)",
    dir: "ltr",
    currency: "CNY",
    numberingSystem: "standard",
  },
  "zh-HK": {
    label: "Chinese (Hong Kong)",
    dir: "ltr",
    currency: "HKD",
    numberingSystem: "standard",
  },
  "zh-TW": {
    label: "Chinese (Traditional)",
    dir: "ltr",
    currency: "TWD",
    numberingSystem: "standard",
  },
  "zu-ZA": {
    label: "Zulu",
    dir: "ltr",
    currency: "ZAR",
    numberingSystem: "standard",
  }
} as const;

/**
 * Validate if a locale is supported
 */
export function isValidLocale(locale: string): locale is SupportedLocale {
  return SUPPORTED_LOCALES.includes(locale as SupportedLocale);
}

/**
 * Get the best matching locale from the browser
 */
export function getBrowserLocale(): SupportedLocale {
  if (typeof window === 'undefined') return DEFAULT_LOCALE;
  
  const browserLocales = navigator.languages || [navigator.language];
  
  for (const locale of browserLocales) {
    // Try exact match
    if (isValidLocale(locale)) {
      return locale;
    }
    
    // Try base language match (e.g. "en" -> "en-US")
    const baseLang = locale.split('-')[0];
    const match = SUPPORTED_LOCALES.find(l => l.startsWith(baseLang + '-'));
    if (match) {
      return match;
    }
  }
  
  return DEFAULT_LOCALE;
}

/**
 * Get a valid locale from a string or return default
 */
export function getValidLocale(locale: string | undefined | null): SupportedLocale {
  if (!locale) return DEFAULT_LOCALE;
  if (isValidLocale(locale)) return locale;
  return DEFAULT_LOCALE;
}
