// Map slug variations to canonical filenames
export const SLUG_TO_FILENAME: Record<string, string> = {
  'tanium-platform-foundation': '00-tanium-platform-foundation.mdx',
  'platform-foundation': '00-tanium-platform-foundation.mdx',
  '00-tanium-platform-foundation-v2': '00-tanium-platform-foundation-v2.mdx',
  'tanium-platform-foundation-v2': '00-tanium-platform-foundation-v2.mdx',
  'platform-foundation-v2': '00-tanium-platform-foundation-v2.mdx',
  'asking-questions': '01-asking-questions.mdx',
  'asking-questions-learn': '01-asking-questions-learn.mdx',
  'refining-questions-targeting': '02-refining-questions-targeting.mdx',
  'refining-questions': '02-refining-questions-targeting.mdx',
  'taking-action-packages-actions': '03-taking-action-packages-actions.mdx',
  'taking-action': '03-taking-action-packages-actions.mdx',
  'navigation-basic-modules': '04-navigation-basic-modules.mdx',
  navigation: '04-navigation-basic-modules.mdx',
  'reporting-data-export': '05-reporting-data-export.mdx',
  reporting: '05-reporting-data-export.mdx',
  'microlearning-example': 'MICROLEARNING_EXAMPLE.mdx',
  'example-module-microlearning': 'MICROLEARNING_EXAMPLE.mdx',
  MICROLEARNING_EXAMPLE: 'MICROLEARNING_EXAMPLE.mdx',
};
