#!/bin/bash
###############################################################################
# Git Pre-Commit Hook Setup for Auto-Translation
#
# This script installs a pre-commit hook that automatically translates
# all locale files when en-US.json is modified.
#
# Usage:
#   chmod +x scripts/setup-git-hooks.sh
#   ./scripts/setup-git-hooks.sh
#
# What it does:
# 1. Creates .git/hooks/pre-commit (backs up existing hook if present)
# 2. Hook detects if src/i18n/messages/en-US.json is staged
# 3. Runs npm run translate:incremental --staged
# 4. Stages all updated locale files
# 5. Allows commit to proceed with all translations
#
# Developer workflow:
#   $ git add src/i18n/messages/en-US.json
#   $ git commit -m "Add new feature label"
#   [Hook automatically translates 113 locales in ~15-30 seconds]
#   $ git push
###############################################################################

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Git Pre-Commit Hook Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if we're in a git repository
if [ ! -d .git ]; then
  echo -e "${RED}❌ Error: Not a git repository${NC}"
  echo "   Run this script from the project root"
  exit 1
fi

# Check if npm is available
if ! command -v npm &> /dev/null; then
  echo -e "${RED}❌ Error: npm not found${NC}"
  echo "   Please install Node.js and npm"
  exit 1
fi

# Backup existing pre-commit hook if it exists
HOOK_PATH=".git/hooks/pre-commit"
BACKUP_PATH=".git/hooks/pre-commit.backup"

if [ -f "$HOOK_PATH" ]; then
  echo -e "${YELLOW}⚠️  Existing pre-commit hook found${NC}"
  echo "   Backing up to: $BACKUP_PATH"
  cp "$HOOK_PATH" "$BACKUP_PATH"
  echo ""
fi

# Create the pre-commit hook
echo "📝 Creating pre-commit hook..."

cat > "$HOOK_PATH" << 'HOOK_SCRIPT'
#!/bin/bash
###############################################################################
# Auto-Translation Pre-Commit Hook
#
# Automatically translates locale files when en-US.json is modified.
# Generated by scripts/setup-git-hooks.sh
###############################################################################

# Source file to watch
SOURCE_FILE="src/i18n/messages/en-US.json"

# Check if en-US.json is staged
if git diff --cached --name-only | grep -q "^${SOURCE_FILE}$"; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Auto-Translation Hook"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "📋 Detected changes in ${SOURCE_FILE}"
  echo "⚡ Running incremental translation..."
  echo ""

  # Run incremental translation (only changed keys)
  if npm run translate:incremental -- --staged; then
    echo ""
    echo "✅ Translation complete!"
    echo "📦 Staging translated locale files..."

    # Stage all locale files (113 locales + en-US.json)
    git add src/i18n/messages/*.json

    echo "✅ All locale files staged"
    echo ""
  else
    echo ""
    echo "❌ Translation failed!"
    echo "   Fix errors and try again"
    echo ""
    exit 1
  fi
fi

# Allow commit to proceed
exit 0
HOOK_SCRIPT

# Make hook executable
chmod +x "$HOOK_PATH"

echo -e "${GREEN}✅ Pre-commit hook installed!${NC}"
echo ""

# Verify installation
echo "🔍 Verification:"
echo "   Hook location: $HOOK_PATH"
echo "   Executable: $([ -x "$HOOK_PATH" ] && echo 'Yes' || echo 'No')"
echo ""

# Test if translate:incremental script exists
if grep -q '"translate:incremental"' package.json; then
  echo -e "${GREEN}✅ translate:incremental script found${NC}"
else
  echo -e "${RED}❌ translate:incremental script not found in package.json${NC}"
  echo "   Add the script to package.json:"
  echo '   "translate:incremental": "tsx scripts/translate-incremental.ts"'
  exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}  Setup Complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 How it works:"
echo ""
echo "   1. Edit src/i18n/messages/en-US.json"
echo "   2. Stage your changes: git add src/i18n/messages/en-US.json"
echo "   3. Commit: git commit -m 'Add new labels'"
echo "   4. Hook automatically:"
echo "      • Detects changed translation keys"
echo "      • Translates to 113 locales (~15-30 seconds)"
echo "      • Stages all 114 locale files"
echo "      • Commit includes everything"
echo ""
echo "💡 Tips:"
echo "   • Only changed keys are translated (fast!)"
echo "   • Cache prevents re-translating unchanged keys"
echo "   • To skip hook: git commit --no-verify"
echo "   • To uninstall: rm .git/hooks/pre-commit"
echo ""
echo -e "${GREEN}✨ Zero-friction translation automation enabled!${NC}"
echo ""
