name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm run test --if-present

      # Optionally build (set dummy env to avoid production client throwing on missing keys)
      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: http://localhost
          NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy
        run: npm run build --if-present

